version: "3.0"

services:
  php:
    container_name: "${PROJECT_NAME}_php"
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    image: "cy83rt00n/ctn_docker:isp-cp_php"
    volumes:
      - ./phalcon:/var/www/html
    environment:
      project_database_name: ${DB_NAME}
  react:
    container_name: "${PROJECT_NAME}_react"
    command: ["serve", "-s", "build", "-l", "3000"]
    build:
      context: .
      dockerfile: dockerfiles/react.dockerfile
    image: "cy83rt00n/ctn_docker:isp-cp_react"
    working_dir: /app
    volumes:
      - ./react:/app
    ports:
      - "80:3000"
      - "35729:35729"
  nginx:
    container_name: "${PROJECT_NAME}_www"
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    image: "cy83rt00n/ctn_docker:isp-cp_nginx"
    volumes:
      - ./phalcon/public:/var/www/html
      - ./config/nginx/0-${PROJECT_ENV}.${PROJECT_NAME}.conf:/etc/nginx/conf.d/0-${PROJECT_ENV}.${PROJECT_NAME}.conf
    ports:
      - "8080:80"
  mariadb:
      container_name: "${PROJECT_NAME}_db"
      build:
        context: .
        dockerfile: dockerfiles/mariadb.dockerfile
      image: "cy83rt00n/ctn_docker:isp-cp_mariadb"
      environment:
        MYSQL_ROOT_PASSWORD: secret
        project_database_name: ${DB_NAME}
      volumes:
        - ./database/mysql:/docker-entrypoint-initdb.d