version: "3.0"

services:
  php:
    container_name: "${PROJECT_NAME}_php"
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
# It can be useful in future
#    image: phalconphp/php-fpm
    volumes:
      - ./www:/var/www/html
    environment:
      project_database_name: ${DB_NAME}
  react:
    container_name: "${PROJECT_NAME}_react"
    command: ["serve", "-s", "build", "-l", "3000"]
    build:
      context: .
      dockerfile: dockerfiles/react.dockerfile
    working_dir: /app
    volumes:
      - ./www/react:/app
    ports:
      - "80:3000"
      - "35729:35729"
  nginx:
    container_name: "${PROJECT_NAME}_www"
    image: nginx:latest
    volumes:
      - ./www:/var/www/html
      - ./config/nginx/0-${PROJECT_ENV}.${PROJECT_NAME}.conf:/etc/nginx/conf.d/0-${PROJECT_ENV}.${PROJECT_NAME}.conf
    ports:
      - "8080:80"
  mariadb:
      container_name: "${PROJECT_NAME}_db"
      image: mariadb:latest
      environment:
        MYSQL_ROOT_PASSWORD: secret
        project_database_name: ${DB_NAME}
      volumes:
        - ./database/mysql:/docker-entrypoint-initdb.d